name: Build APK

on:
  push:
    branches: [ "main" ]  # Змініть на master, якщо ваша гілка master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/kivy/buildozer:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Android SDK Manager and Licenses
      run: |
        # 1. Створюємо правильну сучасну структуру папок для cmdline-tools всередині Docker
        mkdir -p /github/home/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        mkdir -p /github/home/.buildozer/android/platform/android-sdk/licenses

        # 2. Завантажуємо ОФІЦІЙНИЙ стабільний пакет інструментів від Google (cmdline-tools)
        wget -q https://google.com -O /tmp/cmdline-tools.zip
        
        # 3. Розпаковуємо утиліти Google безпосередньо у робочу зону Buildozer
        unzip -q /tmp/cmdline-tools.zip -d /tmp/cmdline-out
        mv /tmp/cmdline-out/cmdline-tools/* /github/home/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
        
        # 4. Створюємо фейковий місток для застарілої перевірки Buildozer (щоб він не шукає tools/bin)
        mkdir -p /github/home/.buildozer/android/platform/android-sdk/tools/bin
        ln -s /github/home/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager /github/home/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

        # 5. Записуємо актуальні цифрові ліцензії Google, щоб робота не переривалася
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > /github/home/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" >> /github/home/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "6c1769a36595e6ae1e4fbee2d9931ef1130252af" >> /github/home/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "893543563402757754d5b78ae383bc5d1792d1f0" > /github/home/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

    - name: Build APK with Buildozer
      run: |
        git config --global --add safe.directory '*'
        
        # Запускаємо автоматичну збірку з потоком відповідей "yes"
        yes | buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
